### ISSUE TITLE
Final Checklist

### ISSUE THREAD

**Issue by fgregg** [datamade/nyc-councilmatic#39]
## Framing / Call to Action
- [x] Make sure that the site has a clear call to action. This should not be 'hey look at this cool tool'. Rather, it should be a way for someone to engage in a meaningful way on the issue being presented.

Some examples:
- Join a mailing list (which means you need to create one)
- Attend an event
- Share on Facebook/Twitter
- Donate to a particular organization
- Create a Tumblr for people to share interesting findings (if it's a data access site)
## Web Search Indexing
- [x] If you have a staging site, tell the search engine robots not to index you with a robots.txt
- [x] Make sure you allow indexing when you are ready to launch.
## Google Analytics
- [x] Create [Google Analytics](http://www.google.com/analytics/) account
- [x] Hook up the GA Tracking Code (typically in our `analytics_lib.js` file)
- [ ] Set up relevant Goals and Funnels
- [x] Set up [Google Webmaster Tools](https://www.google.com/webmasters/tools/home?hl=en)
- [x] Verify site in Webmaster Tools with DNS TXT record
- [x] Link Webmaster Tools to Google Analytics
## Sharing & Rich Snippets
- [x] Set up general meta tags
  - `<meta name=“description”>`
  - `<meta name=“author”>`
- [x] Set up Facebook meta tags & validate [here](https://developers.facebook.com/tools/debug/)
  - `<meta property=“og:site_name”>`
  - `<meta property=“og:title”>`
  - `<meta property=“og:type”>`
  - `<meta property=“og:description”>`
  - `<meta property=“og:url”>`
  - `<meta property=“og:image”>`
- [x] Set up Twitter meta tags & validate [here](https://cards-dev.twitter.com/validator)
  - `<meta name=“twitter:card”>`
  - `<meta name=“twitter:site”>`
  - `<meta name=“twitter:creator”>`
  - `<meta name=“twitter:description”>` (note that this needs to be under 200 characters)
  - `<meta name=“twitter:title”>`
  - `<meta name=“twitter:url”>`
  - `<meta name=“twitter:image:src”>`
- [ ] Create 2-5 meme images using [Canva](http://canva.com/) or a similar tool
## Mobile Friendliness

Test on various mobile devices:
- [x] scrolling is easy
- [x] nav bar works
- [x] hoverable things are tappable
- [x] charts/maps look ok

Using localtunnel to test a site running locally:
1. `npm install -g localtunnel`
2. `lt --port 5000` (or replace 5000 w/ whatever port you're using)
3. navigate to the url that localtunnel gives you
## Load Testing

If your site relies on a database or server-side code, it should use caching and be load tested. If it's a static HTML or Jekyll site, you can skip this section.
- [x] set up page [caching](https://en.wikipedia.org/wiki/Web_cache)
- [ ] write a script to load test all your pages. [Here's a good example from Illinois Sunshine](https://github.com/datamade/illinois-sunshine/blob/master/cache_builder.py)
## Readme

If the site is open source, make sure the Readme.md is complete and accurate. 

Here's a few good examples:
- [Geomancer](https://github.com/associatedpress/geomancer/blob/master/README.md)
- [Illinois Sunshine](https://github.com/datamade/illinois-sunshine/blob/master/README.md)

The Readme should have the following sections:
- [ ] Overview
- [x] Setup
- [x] Running locally
- [x] Team
- [x] Errors / Bugs 
- [x] Pull Requests
- [x] Copyright and License
## Outreach
- [ ] Write up press release
- [x] Identify who will be the primary person of contact and make their info prominent on the website and all PR
- [x] Identify relevant media contacts to email
- [ ] Identify relevant social news sites (reddit, listservs, slack channels)
- [ ] Divide & conquer - send out the media blitz!

**Comment by davidmooreppf** [comment]
Just noting, on my end, tomorrow I was planning to do the following from SF: publish a PPF blog post based on previous About page copy, email out preview links to people who signed-up with interest in Councillmatic, email to friends-of-PPF, going out on Twitter & Facebook, and then later this month, blast emails to our larger list. 

There's also the following list-servs for possible previews, will coordinate with you Derek before I start sending. Realize you're traveling, will be easy to briefly chat tmw. 
- CFA Brigades
- CFA Muni-Innovation
- Sunlight Fdn Blog & Social
- Sunlight Labs
- GovLab Academy 
- Civicist
- Lots more city umbrella organizations from AskThem launch, can detail.
