### ISSUE TITLE
front-end polish

### ISSUE THREAD

**Issue by cathydeng** [datamade/nyc-councilmatic#50]
misc things we should do before launching

**colors**
- [x] change color scheme & fonts for nyc-specific look/feel, once we have the logo
- [x] consistent coloring between bill status labels & bill action text
- [x] higher contrast on bill abstract (#78)
- [x] higher contrast on committee labels (#78)

**images**
- [x] add photo to homepage
- [x] add favicon
- [x] add logo
- [x] add images to featured bills

**mobile**
- [x] fix nav bar jank
- [x] style search bar on search page for mobile (like on home page)
- [x] fix collapse accordion on search page for mobile (#60)
- [x] style tabs on bill page & person page for mobile
- [x] style status pane on bill page for mobile
- [x] style info pane on person page for mobile
- [x] style tables for mobile

**other**
- [x] style contents of search filter (#60)
- [x] add button to see all events on home page (#60)
- [x] style date selecter on events page
- [x] style legislation item partial like passed legislation item partial (#79)
- [x] larger clickable area on bill listing for passed bills (#75)
